### ISSUE TITLE
Utilizing the models developed in the bacLIFE paper (Pseudomonas/Burkholderia)

### ISSUE THREAD

**Issue by azam17** [Carrion-lab/bacLIFE#12]
Hi,

is it possible for the end user to utilize the machine learning models (Pseudomonas/Burkholderia) utilized in the original paper of bacLIFE?

Regards,
Zuhairi

**Comment by gguerr001** [comment]
Hi Zuhairi,

In the wiki https://github.com/Carrion-lab/bacLIFE/wiki/bacLIFE-wiki you can find a section called "Lifestyle prediction module" with the instructions of how to train and use the same machine learning as in our paper.

**Comment by azam17** [comment]
Thanks for the reply. i have an additional question. I managed to finish the snakemake step but i forget to include one important genome in the snakemake run. How do i go about it to include the missing genome in the final output? What step need to be taken to rerun the snakemake step to create outputs that include that genome without starting all over again with all the process.

**Comment by gguerr001** [comment]
Hi, We are working in add a function to add individual genomes to a bacLIFE run but for now is still in developement. The best way to avoid any error would be start from the beggining.

**Comment by azam17** [comment]
Okay noted. i managed to launch the Shiny app to analyze my data. may i know the possible reason why the permanova test showed as error?

![Screenshot 2024-07-09 111354](https://github.com/Carrion-lab/bacLIFE/assets/21982727/baa97421-ace5-4e13-adaa-99d0ca160006)

**Comment by gguerr001** [comment]
Hi, I need more information to know. Do you see any "NA" class in the legend of the PCoA above. If you have in the PCoA plot genomes with "NA" lifestyle there could be a missmatch between names in the MEGAMATRIX_renamed.txt file and in the mapping_file.txt.
