### ISSUE TITLE
Lifestyle classifier error

### ISSUE THREAD

**Issue by arunprasanna83** [Carrion-lab/bacLIFE#14]
Hi,
I am testing around 77 bacteria. clustering module is successful. While the lifestyle prediction module failed with following error.

> ----Running random forest for class: Nonbeneficial-----
> Features selected for modelling saved as: classifier/features_Nonbeneficial
> ROC plot saved as: classifier/ROC_Nonbeneficial
> Traceback (most recent call last):
>   File "/home/nagaraap/Documents/bacLIFE/classifier_src/FS_RF2.py", line 190, in <module>
>     X_new_fs = fs.transform(X_new)
>                ^^^^^^^^^^^^^^^^^^^
>   File "/home/nagaraap/Downloads/miniconda3/envs/bacLIFE_environment/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
>     data_to_wrap = f(self, X, *args, **kwargs)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/nagaraap/Downloads/miniconda3/envs/bacLIFE_environment/lib/python3.12/site-packages/sklearn/feature_selection/_base.py", line 102, in transform
>     X = self._validate_data(
>         ^^^^^^^^^^^^^^^^^^^^
>   File "/home/nagaraap/Downloads/miniconda3/envs/bacLIFE_environment/lib/python3.12/site-packages/sklearn/base.py", line 633, in _validate_data
>     out = check_array(X, input_name="X", **check_params)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/nagaraap/Downloads/miniconda3/envs/bacLIFE_environment/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1087, in check_array
>     raise ValueError(
> ValueError: Found array with 0 sample(s) (shape=(0, 10582)) while a minimum of 1 is required by SelectKBest.

Does it mean that no statistically significant trait differentiates the group? or the number of samples not enough for training?

Thanks in advance.

**Comment by gguerr001** [comment]
Hi,

A potential reason for the issue is that the genomes to be predicted are not labeled correctly (or there is no genomes to predict at all). Is important that in the `mapping_file.txt` with the metadata information the genomes that need to be predicted need to be labeled as `Unknown` in the Lifestyle column. If you don't have any genome that need to be predicted try to change a couple of them to 'Unknown'  to see if it works. 

Let me know if it works!

**Comment by arunprasanna83** [comment]
> Hi,
> 
> A potential reason for the issue is that the genomes to be predicted are not labeled correctly (or there is no genomes to predict at all). Is important that in the `mapping_file.txt` with the metadata information the genomes that need to be predicted need to be labeled as `Unknown` in the Lifestyle column. If you don't have any genome that need to be predicted try to change a couple of them to 'Unknown' to see if it works.
> 
> Let me know if it works!

Yes you are right. In my metadata, I only had two groups and I did not label any unknown. I will try it and update you.

Thanks.
