### ISSUE TITLE
Error in rule extract_binary_table_GCF

### ISSUE THREAD

**Issue by frafava454** [Carrion-lab/bacLIFE#22]
Hi,

I'm new to using the bacLIFE pipeline for analyzing genomes. I've been encountering various issues, including errors during the big_scape, EGGnog, and antismash steps.

After trying to troubleshoot these problems, I decided to uninstall and reinstall all necessary packages. Surprisingly, this seemed to resolve the previous errors.

However, I'm now facing a new issue:
Error in rule extract_binary_table_GCF:
    jobid: 31
    input: intermediate_files/BiG-SCAPE/bigscape_output/network_files/hybrids_glocal/mix/mix_clustering_c0.70.tsv, intermediate_files/BiG-SCAPE/bigscape_output/network_files/hybrids_glocal/mix/mix_c0.70.network, intermediate_files/BiG-SCAPE/bigscape_output/network_files/hybrids_glocal/Network_Annotations_Full.tsv
    output: intermediate_files/BiG-SCAPE/mix_filtered.network, intermediate_files/BiG-SCAPE/annotation.txt, intermediate_files/BiG-SCAPE/GCF_annotation.txt, intermediate_files/BiG-SCAPE/abs_pres_table.csv, intermediate_files/BiG-SCAPE/big_scape_binary_table.txt

[1] "Merge with absence_presence_matrix"
[1] "Write MEGAMATRIX"
[Wed Nov 13 11:49:56 2024]
Finished job 23.
30 of 34 steps (88%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-11-13T101236.345389.snakemake.log
WorkflowError:
At least one job did not complete successfully.

I've verified that the file is present in the correct directory and it's not empty. Could you please help me understand the cause of this error and suggest potential solutions?

**Comment by kevinbretscher** [comment]
Hi could you share the complete log file (.snakemake/log/2024-11-13T101236.345389.snakemake.log) here?

**Comment by frafava454** [comment]
[2024-11-13T101236.345389.snakemake.log](https://github.com/user-attachments/files/17736104/2024-11-13T101236.345389.snakemake.log)
Here it is

**Comment by frafava454** [comment]
I don't know why but I run again the program and this time finished. The output are not the best I'm going to check them. 
Thanks for help me.

**Comment by kevinbretscher** [comment]
Glad to hear it works now. I did not see a specific error so maybe a process just got stuck. For the output/best results I would generally recommend to run baclife on bacteria from the same genus or on bacteria that are at least somewhat phylogenetically related and to have a decent amount of genomes (10-20 per lifestyle or trait).
