### ISSUE TITLE
Minimal number of genomes needed

### ISSUE THREAD

**Issue by sentausa** [Carrion-lab/bacLIFE#5]
Hi,

This seems to be a very interesting tool. I wonder how many genomes (with annotated metadata) are needed at minimum to get a good prediction of the bacterial lifestyle?

Thank you.

**Comment by Carrion-lab** [comment]
Hi Sentausa,

thanks for your kind words. Please see this text extracted from the methods sections:

Although bacLIFE is designed for big datasets, it can be used for small datasets with few genomes if there is a very strong association between genes and lifestyles; of course, as in all such statistical analyses, the more genomic observations are available in the input data, the more power the analysis will have. Crucial for the success rate is to have an approximate minimum of 10 genomes per lifestyle in the comparative analysis to have reliable statistics.

best wishes,
victor.

**Comment by sentausa** [comment]
Ah, I didn't see that. But only 10? That's fantastic! Are there any further details in the paper or in the supplementary materials that support/show this? And thanks for the quick reply!
