### ISSUE TITLE
Antismash rule error

### ISSUE THREAD

**Issue by vishnukumar200102** [Carrion-lab/bacLIFE#6]
[01:31:53] Thank you, come again.
[Sun Mar 24 01:31:54 2024]
Finished job 391.
712 of 2149 steps (33%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-03-23T153649.776647.snakemake.log
WorkflowError:
At least one job did not complete successfully.

**Comment by vishnukumar200102** [comment]
[Uploading error.docx…]()

**Comment by vishnukumar200102** [comment]
[Sun Mar 24 01:02:55 2024]
Job 110: executing prokka.
Reason: Missing output files: intermediate_files/annot/chitinolyticus_X00100_O/Paenibacillus_chitinolyticus_X00100_O.gbk; Input files updated by another job: .mkdir.chkpnt

[Sun Mar 24 01:05:21 2024]
Finished job 5.
649 of 2149 steps (30%) done
Select jobs to execute...
Execute 1 jobs...

[Sun Mar 24 01:05:22 2024]
localrule antismash:
    input: intermediate_files/annot/sp_X00496_O/Paenibacillus_sp_X00496_O.gbk
    output: intermediate_files/antismash/Paenibacillus_sp_X00496_O/Paenibacillus_sp_X00496_O.gbk
    jobid: 1879
    reason: Missing output files: intermediate_files/antismash/Paenibacillus_sp_X00496_O/Paenibacillus_sp_X00496_O.gbk; Input files updated by another job: intermediate_files/annot/sp_X00496_O/Paenibacillus_sp_X00496_O.gbk
    wildcards: genus=Paenibacillus, species=sp, str=X00496, replicon=O
    resources: tmpdir=/tmp

[Sun Mar 24 01:05:22 2024]
Error in rule antismash:
    jobid: 1879
    input: intermediate_files/annot/sp_X00496_O/Paenibacillus_sp_X00496_O.gbk
    output: intermediate_files/antismash/Paenibacillus_sp_X00496_O/Paenibacillus_sp_X00496_O.gbk
    shell:
        set +u; source /opt/miniconda3/etc/profile.d/conda.sh; conda activate antismash_bacLIFE; set -u; antismash --cb-general --cb-knownclusters --cb-subclusters --output-dir intermediate_files/antismash/Paenibacillus_sp_X00496_O/ -c 5 --asf --pfam2go --genefinding-tool prodigal --smcog-trees intermediate_files/annot/sp_X00496_O/Paenibacillus_sp_X00496_O.gbk
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by gguerr001** [comment]
Hi, can you send the full log file so we can have more information about the error

 .snakemake/log/2024-03-23T153649.776647.snakemake.log

**Comment by vishnukumar200102** [comment]
Sir,
Herewith I have attached the log file for the error.

Thank you for your response.

**Comment by vishnukumar200102** [comment]
[2024-03-23T153649.776647.snakemake.log](https://github.com/Carrion-lab/bacLIFE/files/14736018/2024-03-23T153649.776647.snakemake.log)
Thank you for response sir

**Comment by ismathsadhir** [comment]
I am no expert, however, there was a couple of instances when antismash gave me errors on my initial attempts. I could resolve these and I hope it might be of help to you

1) The first-time error was rectified by providing the correct path on line 284 and 303 of snakefile. Instead of **/opt/miniconda3/** I had to specify **/home/user/anaconda/** and it worked

2) The second-time error was rectified by specifying fewer number of jobs (snakemake -j 2 for 32GB RAM and snakemake -j 12 for 128GB RAM). I could observe that the RAM usage is through the roof when I tried to run 16 jobs and I guess insufficient RAM might have been the issue in this case.

**Comment by vishnukumar200102** [comment]
Thank you for your response sir, I will try and inform you as soon as
possible.

**Comment by gguerr001** [comment]
Thanks @ismathsadhir for the help!
I've conducted some testing and updated the conda activate commands on lines 284 and 303 to source activate, which doesn't required the installation path of conda to work. This adjustment will help prevent errors caused by variations in the installation location of conda across different systems. Please @vishnukumar200102. let us know if this fix your error

**Comment by vishnukumar200102** [comment]
Herewith I attached the error log file, same issue.

**Comment by vishnukumar200102** [comment]
[2024-03-25T152234.485591.snakemake.log](https://github.com/Carrion-lab/bacLIFE/files/14741824/2024-03-25T152234.485591.snakemake.log)

**Comment by gguerr001** [comment]
@vishnukumar200102 You are still using the non-updated Snakefile by what I see in you log. Use the new updated Snakefile from the github

**Comment by vishnukumar200102** [comment]
[2024-03-25T170712.236625.snakemake.log](https://github.com/Carrion-lab/bacLIFE/files/14742856/2024-03-25T170712.236625.snakemake.log)
Sir this is run by 3 weeks ago, updated snake file

**Comment by gguerr001** [comment]
Could you try to run a single instance of antismash to see what could be the error. The snakemake log doesn't seem to tell the specific error. You have to activate the conda environment "conda activate antismash_bacLIFE" and run one of the instances that gives you an error. For example:

"antismash --cb-general --cb-knownclusters --cb-subclusters --output-dir intermediate_files/antismash/Paenibacillus_germinis_X00158_O/ -c 5 --asf --pfam2go --genefinding-tool prodigal --smcog-trees intermediate_files/annot/germinis_X00158_O/Paenibacillus_germinis_X00158_O.gbk"

Maybe this way we can find the specific problem you are having with antismash
